name: Build

on:
  push:
    branches: [ master, stable, dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2004

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: plausible/analytics:${{ steps.extract_branch.outputs.branch }}
          cache-from: type=registry,ref=plausible/analytics:${{ steps.extract_branch.outputs.branch }}
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
